// Generated by scripts/generate-seed.mjs — do not edit by hand.
// Sample catalogue used when Supabase env vars are absent, so the app runs
// on a fresh clone. Regenerate with: node scripts/generate-seed.mjs
import type { Collection, Product } from "./types";

export const FALLBACK_PRODUCTS: Product[] = [
  {
    "id": "fallback-0",
    "slug": "macaron",
    "sku": "CLK-001",
    "name": "Macaron — Clicker keychain",
    "short_name": "Macaron",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized macaron with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food.",
    "price": 900,
    "art": "macaron",
    "tint": "blush",
    "gallery": [
      {
        "art": "macaron",
        "tint": "blush",
        "alt": "Macaron — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized macaron with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 32,
    "stock_on_hand": 3,
    "is_bestseller": true,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-1",
    "slug": "cinnamon-roll",
    "sku": "CLK-002",
    "name": "Cinnamon roll — Clicker keychain",
    "short_name": "Cinnamon roll",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized cinnamon roll with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food.",
    "price": 900,
    "art": "cinnamon",
    "tint": "butter",
    "gallery": [
      {
        "art": "cinnamon",
        "tint": "butter",
        "alt": "Cinnamon roll — front view"
      }
    ],
    "colours": [
      {
        "name": "Light Brown",
        "hex": "#B08968"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized cinnamon roll with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 35,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-2",
    "slug": "s-mores",
    "sku": "CLK-003",
    "name": "S'mores — Clicker keychain",
    "short_name": "S'mores",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized s'mores with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food.",
    "price": 900,
    "art": "smore",
    "tint": "butter",
    "gallery": [
      {
        "art": "smore",
        "tint": "butter",
        "alt": "S'mores — front view"
      }
    ],
    "colours": [
      {
        "name": "Light Brown",
        "hex": "#B08968"
      },
      {
        "name": "Dark Brown",
        "hex": "#5B4636"
      },
      {
        "name": "White",
        "hex": "#FFFFFF"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized s'mores with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 38,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-3",
    "slug": "sushi-roll",
    "sku": "CLK-006",
    "name": "Sushi roll — Clicker keychain",
    "short_name": "Sushi roll",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized sushi roll with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food.",
    "price": 900,
    "art": "sushi",
    "tint": "sky",
    "gallery": [
      {
        "art": "sushi",
        "tint": "sky",
        "alt": "Sushi roll — front view"
      }
    ],
    "colours": [
      {
        "name": "Black",
        "hex": "#2B2B2B"
      },
      {
        "name": "Red",
        "hex": "#D64545"
      },
      {
        "name": "Baby Green",
        "hex": "#BFD6A8"
      },
      {
        "name": "Dark Green",
        "hex": "#3F5D3A"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized sushi roll with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 7,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-4",
    "slug": "italian-ice-cup",
    "sku": "CLK-008",
    "name": "Italian ice cup — Clicker keychain",
    "short_name": "Italian ice cup",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized italian ice cup with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food.",
    "price": 900,
    "art": "icecream",
    "tint": "blush",
    "gallery": [
      {
        "art": "icecream",
        "tint": "blush",
        "alt": "Italian ice cup — front view"
      }
    ],
    "colours": [
      {
        "name": "Baby Green",
        "hex": "#BFD6A8"
      },
      {
        "name": "Baby Blue",
        "hex": "#BCD3E8"
      },
      {
        "name": "Baby Pink",
        "hex": "#F6CFD8"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized italian ice cup with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 13,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-5",
    "slug": "ice-cream-cone",
    "sku": "CLK-009",
    "name": "Ice cream cone — Clicker keychain",
    "short_name": "Ice cream cone",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized ice cream cone with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food.",
    "price": 900,
    "art": "icecream",
    "tint": "blush",
    "gallery": [
      {
        "art": "icecream",
        "tint": "blush",
        "alt": "Ice cream cone — front view"
      }
    ],
    "colours": [
      {
        "name": "Brown",
        "hex": "#8B5E3C"
      },
      {
        "name": "Dark Brown",
        "hex": "#5B4636"
      },
      {
        "name": "Baby Pink",
        "hex": "#F6CFD8"
      },
      {
        "name": "Hot Pink",
        "hex": "#E75480"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized ice cream cone with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 16,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-6",
    "slug": "butter",
    "sku": "CLK-013",
    "name": "Butter — Clicker keychain",
    "short_name": "Butter",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized butter with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food.",
    "price": 900,
    "art": "butter",
    "tint": "butter",
    "gallery": [
      {
        "art": "butter",
        "tint": "butter",
        "alt": "Butter — front view"
      }
    ],
    "colours": [
      {
        "name": "Baby Yellow",
        "hex": "#F2D98B"
      },
      {
        "name": "White",
        "hex": "#FFFFFF"
      },
      {
        "name": "Baby Green",
        "hex": "#BFD6A8"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized butter with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 38,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-7",
    "slug": "tiramisu-cake",
    "sku": "CLK-017",
    "name": "Tiramisu Cake — Clicker keychain",
    "short_name": "Tiramisu Cake",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized tiramisu cake with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food.",
    "price": 900,
    "art": "cinnamon",
    "tint": "cream",
    "gallery": [
      {
        "art": "cinnamon",
        "tint": "cream",
        "alt": "Tiramisu Cake — front view"
      }
    ],
    "colours": [
      {
        "name": "Baby Yellow",
        "hex": "#F2D98B"
      },
      {
        "name": "Dark Brown",
        "hex": "#5B4636"
      },
      {
        "name": "White",
        "hex": "#FFFFFF"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized tiramisu cake with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 10,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-8",
    "slug": "fruit-sandwich-in-basket",
    "sku": "CLK-018",
    "name": "Fruit sandwich in basket — Clicker keychain",
    "short_name": "Fruit sandwich in basket",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized fruit sandwich in basket with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Basket is part of the product. Theme: Food.",
    "price": 900,
    "art": "bao",
    "tint": "blush",
    "gallery": [
      {
        "art": "bao",
        "tint": "blush",
        "alt": "Fruit sandwich in basket — front view"
      }
    ],
    "colours": [
      {
        "name": "Light Brown",
        "hex": "#B08968"
      },
      {
        "name": "Red",
        "hex": "#D64545"
      },
      {
        "name": "Green",
        "hex": "#6D9557"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized fruit sandwich in basket with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Basket is part of the product. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 13,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": true,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-9",
    "slug": "pancake-stack-in-frying-pan",
    "sku": "CLK-019",
    "name": "Pancake stack in frying pan — Clicker keychain",
    "short_name": "Pancake stack in frying pan",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized pancake stack in frying pan with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pan is part of the product. Theme: Food.",
    "price": 900,
    "art": "pancake",
    "tint": "butter",
    "gallery": [
      {
        "art": "pancake",
        "tint": "butter",
        "alt": "Pancake stack in frying pan — front view"
      }
    ],
    "colours": [
      {
        "name": "Beige",
        "hex": "#E9DCC4"
      },
      {
        "name": "Light Brown",
        "hex": "#B08968"
      },
      {
        "name": "Yellow",
        "hex": "#F2C94C"
      },
      {
        "name": "Black",
        "hex": "#2B2B2B"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized pancake stack in frying pan with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pan is part of the product. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 16,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": true,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-10",
    "slug": "banh-mi",
    "sku": "CLK-020",
    "name": "Bánh mì — Clicker keychain",
    "short_name": "Bánh mì",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized bánh mì with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food.",
    "price": 900,
    "art": "bao",
    "tint": "cream",
    "gallery": [
      {
        "art": "bao",
        "tint": "cream",
        "alt": "Bánh mì — front view"
      }
    ],
    "colours": [
      {
        "name": "Light Brown",
        "hex": "#B08968"
      },
      {
        "name": "Beige",
        "hex": "#E9DCC4"
      },
      {
        "name": "Green",
        "hex": "#6D9557"
      },
      {
        "name": "Dark Brown",
        "hex": "#5B4636"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized bánh mì with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 29,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-11",
    "slug": "pho-bowl",
    "sku": "CLK-021",
    "name": "Phở bowl — Clicker keychain",
    "short_name": "Phở bowl",
    "category": "Clicker keychain",
    "theme": "Food",
    "description": "A palm-sized phở bowl with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food.",
    "price": 900,
    "art": "bao",
    "tint": "sage",
    "gallery": [
      {
        "art": "bao",
        "tint": "sage",
        "alt": "Phở bowl — front view"
      }
    ],
    "colours": [
      {
        "name": "White",
        "hex": "#FFFFFF"
      },
      {
        "name": "Light Brown",
        "hex": "#B08968"
      },
      {
        "name": "Green",
        "hex": "#6D9557"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized phở bowl with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Food."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 32,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-12",
    "slug": "coffee-set",
    "sku": "CLK-023",
    "name": "Coffee set — Clicker keychain",
    "short_name": "Coffee set",
    "category": "Clicker keychain",
    "theme": "Drinks",
    "description": "A palm-sized coffee set with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Latte art on the surface. Theme: Drinks.",
    "price": 900,
    "art": "coffee",
    "tint": "cream",
    "gallery": [
      {
        "art": "coffee",
        "tint": "cream",
        "alt": "Coffee set — front view"
      }
    ],
    "colours": [
      {
        "name": "Grey",
        "hex": "#9AA0A6"
      },
      {
        "name": "Dark Brown",
        "hex": "#5B4636"
      },
      {
        "name": "Light Brown",
        "hex": "#B08968"
      },
      {
        "name": "White",
        "hex": "#FFFFFF"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized coffee set with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Latte art on the surface. Theme: Drinks."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 38,
    "stock_on_hand": 3,
    "is_bestseller": true,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-13",
    "slug": "matcha-set",
    "sku": "CLK-027",
    "name": "Matcha set — Clicker keychain",
    "short_name": "Matcha set",
    "category": "Clicker keychain",
    "theme": "Drinks",
    "description": "A palm-sized matcha set with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Drinks.",
    "price": 900,
    "art": "matcha",
    "tint": "sage",
    "gallery": [
      {
        "art": "matcha",
        "tint": "sage",
        "alt": "Matcha set — front view"
      }
    ],
    "colours": [
      {
        "name": "Matcha Green",
        "hex": "#A9BC7F"
      },
      {
        "name": "Grey",
        "hex": "#9AA0A6"
      },
      {
        "name": "Light Brown",
        "hex": "#B08968"
      },
      {
        "name": "White",
        "hex": "#FFFFFF"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized matcha set with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Drinks."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 10,
    "stock_on_hand": 3,
    "is_bestseller": true,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-14",
    "slug": "corgi-bum",
    "sku": "CLK-01",
    "name": "Corgi bum — Clicker keychain",
    "short_name": "Corgi bum",
    "category": "Clicker keychain",
    "theme": "Animals",
    "description": "A palm-sized corgi bum with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Animals.",
    "price": 900,
    "art": "corgi",
    "tint": "butter",
    "gallery": [
      {
        "art": "corgi",
        "tint": "butter",
        "alt": "Corgi bum — front view"
      }
    ],
    "colours": [
      {
        "name": "Brown",
        "hex": "#8B5E3C"
      },
      {
        "name": "Baby Orange",
        "hex": "#F3B98A"
      },
      {
        "name": "White",
        "hex": "#FFFFFF"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized corgi bum with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Animals."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.7,
    "review_count": 32,
    "stock_on_hand": 3,
    "is_bestseller": true,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-15",
    "slug": "dog-breeds-set-1",
    "sku": "CLK-031",
    "name": "Dog breeds (set 1) — Clicker keychain",
    "short_name": "Dog breeds (set 1)",
    "category": "Clicker keychain",
    "theme": "Animals in carton box",
    "description": "A palm-sized dog breeds (set 1) with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pug, corgi, dachshund. Theme: Animals in carton box.",
    "price": 900,
    "art": "corgi",
    "tint": "cream",
    "gallery": [
      {
        "art": "corgi",
        "tint": "cream",
        "alt": "Dog breeds (set 1) — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized dog breeds (set 1) with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pug, corgi, dachshund. Theme: Animals in carton box."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 32,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-16",
    "slug": "dog-breeds-set-2",
    "sku": "CLK-032",
    "name": "Dog breeds (set 2) — Clicker keychain",
    "short_name": "Dog breeds (set 2)",
    "category": "Clicker keychain",
    "theme": "Animals in carton box",
    "description": "A palm-sized dog breeds (set 2) with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Frenchie, shiba, husky. Theme: Animals in carton box.",
    "price": 900,
    "art": "corgi",
    "tint": "butter",
    "gallery": [
      {
        "art": "corgi",
        "tint": "butter",
        "alt": "Dog breeds (set 2) — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized dog breeds (set 2) with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Frenchie, shiba, husky. Theme: Animals in carton box."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 35,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-17",
    "slug": "cat-dog-paws",
    "sku": "CLK-035",
    "name": "Cat & dog paws — Clicker keychain",
    "short_name": "Cat & dog paws",
    "category": "Clicker keychain",
    "theme": "Animals",
    "description": "A palm-sized cat & dog paws with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Animals.",
    "price": 900,
    "art": "corgi",
    "tint": "blush",
    "gallery": [
      {
        "art": "corgi",
        "tint": "blush",
        "alt": "Cat & dog paws — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized cat & dog paws with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Animals."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 44,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-18",
    "slug": "capybara",
    "sku": "CLK-039",
    "name": "Capybara — Clicker keychain",
    "short_name": "Capybara",
    "category": "Clicker keychain",
    "theme": "Animals in carton box",
    "description": "A palm-sized capybara with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Animals in carton box.",
    "price": 900,
    "art": "corgi",
    "tint": "cream",
    "gallery": [
      {
        "art": "corgi",
        "tint": "cream",
        "alt": "Capybara — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized capybara with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Animals in carton box."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 16,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-19",
    "slug": "round-cactus-in-pot",
    "sku": "CLK-042",
    "name": "Round cactus in pot — Clicker keychain",
    "short_name": "Round cactus in pot",
    "category": "Clicker keychain",
    "theme": "Plants & flowers",
    "description": "A palm-sized round cactus in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pot-based, same pot shape across the range. Theme: Plants & flowers.",
    "price": 900,
    "art": "cactus",
    "tint": "sage",
    "gallery": [
      {
        "art": "cactus",
        "tint": "sage",
        "alt": "Round cactus in pot — front view"
      }
    ],
    "colours": [
      {
        "name": "Light Brown",
        "hex": "#B08968"
      },
      {
        "name": "Green",
        "hex": "#6D9557"
      },
      {
        "name": "White",
        "hex": "#FFFFFF"
      }
    ],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized round cactus in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pot-based, same pot shape across the range. Theme: Plants & flowers."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 35,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-20",
    "slug": "aloe-in-pot",
    "sku": "CLK-043",
    "name": "Aloe in pot — Clicker keychain",
    "short_name": "Aloe in pot",
    "category": "Clicker keychain",
    "theme": "Plants & flowers",
    "description": "A palm-sized aloe in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pot-based, same pot shape across the range. Theme: Plants & flowers.",
    "price": 900,
    "art": "cactus",
    "tint": "sage",
    "gallery": [
      {
        "art": "cactus",
        "tint": "sage",
        "alt": "Aloe in pot — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized aloe in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pot-based, same pot shape across the range. Theme: Plants & flowers."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 38,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-21",
    "slug": "monstera-in-pot",
    "sku": "CLK-044",
    "name": "Monstera in pot — Clicker keychain",
    "short_name": "Monstera in pot",
    "category": "Clicker keychain",
    "theme": "Plants & flowers",
    "description": "A palm-sized monstera in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pot-based, same pot shape across the range. Theme: Plants & flowers.",
    "price": 900,
    "art": "cactus",
    "tint": "sage",
    "gallery": [
      {
        "art": "cactus",
        "tint": "sage",
        "alt": "Monstera in pot — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized monstera in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pot-based, same pot shape across the range. Theme: Plants & flowers."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 41,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-22",
    "slug": "white-tulip-in-pot",
    "sku": "CLK-046",
    "name": "White tulip in pot — Clicker keychain",
    "short_name": "White tulip in pot",
    "category": "Clicker keychain",
    "theme": "Plants & flowers",
    "description": "A palm-sized white tulip in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pot-based, same pot shape across the range. Theme: Plants & flowers.",
    "price": 900,
    "art": "tulip",
    "tint": "blush",
    "gallery": [
      {
        "art": "tulip",
        "tint": "blush",
        "alt": "White tulip in pot — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized white tulip in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pot-based, same pot shape across the range. Theme: Plants & flowers."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 7,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": true,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-23",
    "slug": "heart-plant-in-pot",
    "sku": "CLK-048",
    "name": "Heart plant in pot — Clicker keychain",
    "short_name": "Heart plant in pot",
    "category": "Clicker keychain",
    "theme": "Plants & flowers",
    "description": "A palm-sized heart plant in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. From the Valentine set. Pot-based, same pot shape across the range. Theme: Plants & flowers.",
    "price": 900,
    "art": "tulip",
    "tint": "blush",
    "gallery": [
      {
        "art": "tulip",
        "tint": "blush",
        "alt": "Heart plant in pot — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized heart plant in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. From the Valentine set. Pot-based, same pot shape across the range. Theme: Plants & flowers."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 13,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-24",
    "slug": "sunflower-in-pot",
    "sku": "CLK-049",
    "name": "Sunflower in pot — Clicker keychain",
    "short_name": "Sunflower in pot",
    "category": "Clicker keychain",
    "theme": "Plants & flowers",
    "description": "A palm-sized sunflower in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Design as a potted plant, not a flat flower head. Pot-based, same pot shape across the range. Theme: Plants & flowers.",
    "price": 900,
    "art": "tulip",
    "tint": "butter",
    "gallery": [
      {
        "art": "tulip",
        "tint": "butter",
        "alt": "Sunflower in pot — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized sunflower in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Design as a potted plant, not a flat flower head. Pot-based, same pot shape across the range. Theme: Plants & flowers."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 16,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-25",
    "slug": "daisy-in-pot",
    "sku": "CLK-050",
    "name": "Daisy in pot — Clicker keychain",
    "short_name": "Daisy in pot",
    "category": "Clicker keychain",
    "theme": "Plants & flowers",
    "description": "A palm-sized daisy in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Design as a potted plant, not a flat flower head. Pot-based, same pot shape across the range. Theme: Plants & flowers.",
    "price": 900,
    "art": "tulip",
    "tint": "cream",
    "gallery": [
      {
        "art": "tulip",
        "tint": "cream",
        "alt": "Daisy in pot — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized daisy in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Design as a potted plant, not a flat flower head. Pot-based, same pot shape across the range. Theme: Plants & flowers."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 29,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-26",
    "slug": "baby-s-breath-in-pot",
    "sku": "CLK-053",
    "name": "Baby's breath in pot — Clicker keychain",
    "short_name": "Baby's breath in pot",
    "category": "Clicker keychain",
    "theme": "Plants & flowers",
    "description": "A palm-sized baby's breath in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pot-based, same pot shape across the range. Theme: Plants & flowers.",
    "price": 900,
    "art": "tulip",
    "tint": "sage",
    "gallery": [
      {
        "art": "tulip",
        "tint": "sage",
        "alt": "Baby's breath in pot — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized baby's breath in pot with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Pot-based, same pot shape across the range. Theme: Plants & flowers."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 38,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-27",
    "slug": "letter-clicker-a-z",
    "sku": "CLK-057",
    "name": "Letter clicker A-Z — Clicker keychain",
    "short_name": "Letter clicker A-Z",
    "category": "Clicker keychain",
    "theme": "Letters & names",
    "description": "A palm-sized letter clicker a-z with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. One row per letter you stock — copy this row down and change the SKU. Theme: Letters & names.",
    "price": 900,
    "art": "letters",
    "tint": "lilac",
    "gallery": [
      {
        "art": "letters",
        "tint": "lilac",
        "alt": "Letter clicker A-Z — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized letter clicker a-z with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. One row per letter you stock — copy this row down and change the SKU. Theme: Letters & names."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 10,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-28",
    "slug": "number-clicker-0-9",
    "sku": "CLK-058",
    "name": "Number clicker 0-9 — Clicker keychain",
    "short_name": "Number clicker 0-9",
    "category": "Clicker keychain",
    "theme": "Letters & names",
    "description": "A palm-sized number clicker 0-9 with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Same — one row per number you stock. Theme: Letters & names.",
    "price": 900,
    "art": "letters",
    "tint": "lilac",
    "gallery": [
      {
        "art": "letters",
        "tint": "lilac",
        "alt": "Number clicker 0-9 — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized number clicker 0-9 with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Same — one row per number you stock. Theme: Letters & names."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 13,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-29",
    "slug": "custom-name-charm",
    "sku": "CLK-059",
    "name": "Custom name charm — Clicker keychain",
    "short_name": "Custom name charm",
    "category": "Clicker keychain",
    "theme": "Letters & names",
    "description": "A palm-sized custom name charm with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Cube letters on a cord. Their 7 base colours x 6 letter colours is a smart, cheap way to look like a range. Theme: Letters & names.",
    "price": 900,
    "art": "letters",
    "tint": "lilac",
    "gallery": [
      {
        "art": "letters",
        "tint": "lilac",
        "alt": "Custom name charm — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 0
      },
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 0
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized custom name charm with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Cube letters on a cord. Their 7 base colours x 6 letter colours is a smart, cheap way to look like a range. Theme: Letters & names."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 16,
    "stock_on_hand": 0,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": true,
    "active": true
  },
  {
    "id": "fallback-30",
    "slug": "custom-number-date-chain",
    "sku": "CLK-061",
    "name": "Custom number / date chain — Clicker keychain",
    "short_name": "Custom number / date chain",
    "category": "Clicker keychain",
    "theme": "Letters & names",
    "description": "A palm-sized custom number / date chain with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Anniversary dates, 143, jersey numbers. Theme: Letters & names.",
    "price": 900,
    "art": "letters",
    "tint": "lilac",
    "gallery": [
      {
        "art": "letters",
        "tint": "lilac",
        "alt": "Custom number / date chain — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized custom number / date chain with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Anniversary dates, 143, jersey numbers. Theme: Letters & names."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 32,
    "stock_on_hand": 0,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": true,
    "active": true
  },
  {
    "id": "fallback-31",
    "slug": "heart",
    "sku": "CLK-063",
    "name": "Heart — Clicker keychain",
    "short_name": "Heart",
    "category": "Clicker keychain",
    "theme": "Letters & names",
    "description": "A palm-sized heart with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Letters & names.",
    "price": 900,
    "art": "letters",
    "tint": "blush",
    "gallery": [
      {
        "art": "letters",
        "tint": "blush",
        "alt": "Heart — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized heart with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Letters & names."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 38,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-32",
    "slug": "star",
    "sku": "CLK-064",
    "name": "Star — Clicker keychain",
    "short_name": "Star",
    "category": "Clicker keychain",
    "theme": "Letters & names",
    "description": "A palm-sized star with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Letters & names.",
    "price": 900,
    "art": "letters",
    "tint": "sky",
    "gallery": [
      {
        "art": "letters",
        "tint": "sky",
        "alt": "Star — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized star with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Letters & names."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 41,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-33",
    "slug": "sports-balls-set",
    "sku": "CLK-073",
    "name": "Sports balls set — Clicker keychain",
    "short_name": "Sports balls set",
    "category": "Clicker keychain",
    "theme": "Sport",
    "description": "A palm-sized sports balls set with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Soccer, tennis, basketball, football. Theme: Sport.",
    "price": 900,
    "art": "tennis",
    "tint": "sky",
    "gallery": [
      {
        "art": "tennis",
        "tint": "sky",
        "alt": "Sports balls set — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized sports balls set with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Soccer, tennis, basketball, football. Theme: Sport."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 38,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-34",
    "slug": "badminton-set-racket-shuttlecock",
    "sku": "CLK-074",
    "name": "Badminton set — racket & shuttlecock — Clicker keychain",
    "short_name": "Badminton set — racket & shuttlecock",
    "category": "Clicker keychain",
    "theme": "Sport",
    "description": "A palm-sized badminton set — racket & shuttlecock with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Sport.",
    "price": 900,
    "art": "tennis",
    "tint": "sage",
    "gallery": [
      {
        "art": "tennis",
        "tint": "sage",
        "alt": "Badminton set — racket & shuttlecock — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized badminton set — racket & shuttlecock with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Sport."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 41,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-35",
    "slug": "tennis-set-racket-ball",
    "sku": "CLK-075",
    "name": "Tennis set — racket & ball — Clicker keychain",
    "short_name": "Tennis set — racket & ball",
    "category": "Clicker keychain",
    "theme": "Sport",
    "description": "A palm-sized tennis set — racket & ball with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Sport.",
    "price": 900,
    "art": "tennis",
    "tint": "sky",
    "gallery": [
      {
        "art": "tennis",
        "tint": "sky",
        "alt": "Tennis set — racket & ball — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized tennis set — racket & ball with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Sport."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 44,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-36",
    "slug": "baseball-set-bat-ball-glove",
    "sku": "CLK-076",
    "name": "Baseball set — bat, ball, glove — Clicker keychain",
    "short_name": "Baseball set — bat, ball, glove",
    "category": "Clicker keychain",
    "theme": "Sport",
    "description": "A palm-sized baseball set — bat, ball, glove with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Sport.",
    "price": 900,
    "art": "tennis",
    "tint": "cream",
    "gallery": [
      {
        "art": "tennis",
        "tint": "cream",
        "alt": "Baseball set — bat, ball, glove — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized baseball set — bat, ball, glove with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Sport."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 7,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-37",
    "slug": "dumbbell",
    "sku": "CLK-077",
    "name": "Dumbbell — Clicker keychain",
    "short_name": "Dumbbell",
    "category": "Clicker keychain",
    "theme": "Sport",
    "description": "A palm-sized dumbbell with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Came from a custom request. Theme: Sport.",
    "price": 900,
    "art": "tennis",
    "tint": "sky",
    "gallery": [
      {
        "art": "tennis",
        "tint": "sky",
        "alt": "Dumbbell — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 100
      },
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 150
      },
      {
        "id": "none",
        "label": "No attachment",
        "price_delta": -50
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized dumbbell with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Came from a custom request. Theme: Sport."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 10,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-38",
    "slug": "personalised-bowl-with-pet-s-name",
    "sku": "PET-002",
    "name": "Personalised bowl with pet's name — Pet",
    "short_name": "Personalised bowl with pet's name",
    "category": "Pet",
    "theme": "Pet",
    "description": "A personalised bowl with pet's name, 3D-printed to order in our Sydney studio. Printed in layered PLA and finished by hand. Personalisation is where the margin is. Theme: Pet.",
    "price": 1800,
    "art": "corgi",
    "tint": "cream",
    "gallery": [
      {
        "art": "corgi",
        "tint": "cream",
        "alt": "Personalised bowl with pet's name — front view"
      }
    ],
    "colours": [],
    "attachments": [],
    "details": [
      {
        "title": "Item details",
        "body": "A personalised bowl with pet's name, 3D-printed to order in our Sydney studio. Printed in layered PLA and finished by hand. Personalisation is where the margin is. Theme: Pet."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 35,
    "stock_on_hand": 0,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": true,
    "active": true
  },
  {
    "id": "fallback-39",
    "slug": "phone-stand",
    "sku": "PHB-001",
    "name": "Phone stand — Phone & bag",
    "short_name": "Phone stand",
    "category": "Phone & bag",
    "theme": "Phone & bag",
    "description": "A phone stand, 3D-printed to order in our Sydney studio. Printed in layered PLA and finished by hand. Theme: Phone & bag.",
    "price": 1500,
    "art": "stand",
    "tint": "sky",
    "gallery": [
      {
        "art": "stand",
        "tint": "sky",
        "alt": "Phone stand — front view"
      }
    ],
    "colours": [],
    "attachments": [],
    "details": [
      {
        "title": "Item details",
        "body": "A phone stand, 3D-printed to order in our Sydney studio. Printed in layered PLA and finished by hand. Theme: Phone & bag."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 32,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": true,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-40",
    "slug": "popsocket",
    "sku": "PHB-002",
    "name": "Popsocket — Phone & bag",
    "short_name": "Popsocket",
    "category": "Phone & bag",
    "theme": "Phone & bag",
    "description": "A popsocket, 3D-printed to order in our Sydney studio. Printed in layered PLA and finished by hand. Theme: Phone & bag.",
    "price": 1500,
    "art": "stand",
    "tint": "cream",
    "gallery": [
      {
        "art": "stand",
        "tint": "cream",
        "alt": "Popsocket — front view"
      }
    ],
    "colours": [],
    "attachments": [],
    "details": [
      {
        "title": "Item details",
        "body": "A popsocket, 3D-printed to order in our Sydney studio. Printed in layered PLA and finished by hand. Theme: Phone & bag."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 35,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-41",
    "slug": "phone-charm-on-strap-cord",
    "sku": "PHB-003",
    "name": "Phone charm on strap cord — Phone & bag",
    "short_name": "Phone charm on strap cord",
    "category": "Phone & bag",
    "theme": "Phone & bag",
    "description": "A phone charm on strap cord, 3D-printed to order in our Sydney studio. Printed in layered PLA and finished by hand. Theme: Phone & bag.",
    "price": 1500,
    "art": "stand",
    "tint": "blush",
    "gallery": [
      {
        "art": "stand",
        "tint": "blush",
        "alt": "Phone charm on strap cord — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 0
      },
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A phone charm on strap cord, 3D-printed to order in our Sydney studio. Printed in layered PLA and finished by hand. Theme: Phone & bag."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 38,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  },
  {
    "id": "fallback-42",
    "slug": "alphabet-bag-charm-on-cord",
    "sku": "PHB-004",
    "name": "Alphabet bag charm on cord — Phone & bag",
    "short_name": "Alphabet bag charm on cord",
    "category": "Phone & bag",
    "theme": "Phone & bag",
    "description": "A alphabet bag charm on cord, 3D-printed to order in our Sydney studio. Printed in layered PLA and finished by hand. Theme: Phone & bag.",
    "price": 1500,
    "art": "letters",
    "tint": "lilac",
    "gallery": [
      {
        "art": "letters",
        "tint": "lilac",
        "alt": "Alphabet bag charm on cord — front view"
      }
    ],
    "colours": [],
    "attachments": [
      {
        "id": "cord",
        "label": "Bag charm cord",
        "price_delta": 0
      },
      {
        "id": "keyring",
        "label": "Keyring",
        "price_delta": 0
      },
      {
        "id": "strap",
        "label": "Phone strap",
        "price_delta": 0
      }
    ],
    "details": [
      {
        "title": "Item details",
        "body": "A alphabet bag charm on cord, 3D-printed to order in our Sydney studio. Printed in layered PLA and finished by hand. Theme: Phone & bag."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 41,
    "stock_on_hand": 0,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": true,
    "active": true
  },
  {
    "id": "fallback-43",
    "slug": "keycap-letter-single",
    "sku": "KEY-001",
    "name": "Keycap letter (single) — Clicker keychain",
    "short_name": "Keycap letter (single)",
    "category": "Clicker keychain",
    "theme": "Letters & names",
    "description": "A palm-sized keycap letter (single) with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Letters & names.",
    "price": 900,
    "art": "letters",
    "tint": "lilac",
    "gallery": [
      {
        "art": "letters",
        "tint": "lilac",
        "alt": "Keycap letter (single) — front view"
      }
    ],
    "colours": [],
    "attachments": [],
    "details": [
      {
        "title": "Item details",
        "body": "A palm-sized keycap letter (single) with a spring-loaded clicker inside — the fidget you keep reaching for. Printed in layered PLA and finished by hand. Theme: Letters & names."
      },
      {
        "title": "Materials & care",
        "body": "PLA bioplastic with a steel clicker mechanism. Keep it out of hot cars and dishwashers."
      }
    ],
    "rating": 4.9,
    "review_count": 32,
    "stock_on_hand": 3,
    "is_bestseller": false,
    "is_new": false,
    "is_personalised": false,
    "active": true
  }
];

export const FALLBACK_COLLECTIONS: Collection[] = [
  {
    "id": "collection-0",
    "slug": "retro-key",
    "name": "Retro Key",
    "cap_colour": "#E9DCC4",
    "letter_colour": "#5B4636",
    "holder_colour": "#B08968",
    "charm_art": "coffee",
    "charm_name": "Tiramisu Cake",
    "tint": "cream",
    "is_popular": false
  },
  {
    "id": "collection-1",
    "slug": "strawberry-milk",
    "name": "Strawberry Milk",
    "cap_colour": "#F6CFD8",
    "letter_colour": "#FFFFFF",
    "holder_colour": "#E75480",
    "charm_art": "icecream",
    "charm_name": "Ice Cream Cone",
    "tint": "blush",
    "is_popular": false
  },
  {
    "id": "collection-2",
    "slug": "matcha-latte",
    "name": "Matcha Latte",
    "cap_colour": "#A9BC7F",
    "letter_colour": "#FFFFFF",
    "holder_colour": "#B08968",
    "charm_art": "matcha",
    "charm_name": "Matcha Set",
    "tint": "sage",
    "is_popular": true
  },
  {
    "id": "collection-3",
    "slug": "blueberry",
    "name": "Blueberry",
    "cap_colour": "#BCD3E8",
    "letter_colour": "#FFFFFF",
    "holder_colour": "#9AA0A6",
    "charm_art": "macaron",
    "charm_name": "Macaron",
    "tint": "sky",
    "is_popular": false
  },
  {
    "id": "collection-4",
    "slug": "mono",
    "name": "Mono",
    "cap_colour": "#FFFFFF",
    "letter_colour": "#252220",
    "holder_colour": "#2B2B2B",
    "charm_art": "smore",
    "charm_name": "S'mores",
    "tint": "cream",
    "is_popular": false
  },
  {
    "id": "collection-5",
    "slug": "butter-toast",
    "name": "Butter Toast",
    "cap_colour": "#F2D98B",
    "letter_colour": "#5B4636",
    "holder_colour": "#E4D5BC",
    "charm_art": "butter",
    "charm_name": "Butter",
    "tint": "butter",
    "is_popular": false
  }
];
